# Use Python image
FROM python:3.10-slim

# Install FFmpeg and system dependencies
RUN apt-get update && apt-get install -y ffmpeg libopus-dev

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install Python requirements
RUN pip install --no-cache-dir -r requirements.txt

# Start the bot
CMD ["python", "main.py"]