-- ============================================================================
-- Supabase database setup for the Khmer Telegram AI/TTS bot
-- Generated from the tables and columns used by:
--   updated_bot_khmer_progress_single_message.py
--
-- Run this entire file once in:
--   Supabase Dashboard -> SQL Editor -> New query -> Run
--
-- SECURITY:
--   The bot server must use SUPABASE_SERVICE_ROLE_KEY.
--   Never expose the service-role/secret key in a browser or Telegram message.
-- ============================================================================

begin;

-- UUID generation used by feature_requests.
create extension if not exists pgcrypto with schema extensions;

-- --------------------------------------------------------------------------
-- Shared updated_at trigger
-- --------------------------------------------------------------------------
create or replace function public.bot_set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- --------------------------------------------------------------------------
-- 1. User preferences and Telegram profile cache
-- --------------------------------------------------------------------------
create table if not exists public.user_prefs (
  user_id bigint primary key,
  username text,
  first_name text,
  gender text not null default 'female',
  speed double precision not null default 1.0,
  tts_model text not null default 'auto',
  last_active timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_prefs_gender_check
    check (gender in ('female', 'male')),
  constraint user_prefs_speed_check
    check (speed >= 0.25 and speed <= 4.0)
);

-- Safe migration support for older deployments.
alter table public.user_prefs add column if not exists username text;
alter table public.user_prefs add column if not exists first_name text;
alter table public.user_prefs add column if not exists gender text default 'female';
alter table public.user_prefs add column if not exists speed double precision default 1.0;
alter table public.user_prefs add column if not exists tts_model text default 'auto';
alter table public.user_prefs add column if not exists last_active timestamptz;
alter table public.user_prefs add column if not exists created_at timestamptz default now();
alter table public.user_prefs add column if not exists updated_at timestamptz default now();

update public.user_prefs set gender = 'female' where gender is null;
update public.user_prefs set speed = 1.0 where speed is null;
update public.user_prefs set tts_model = 'auto' where tts_model is null;
update public.user_prefs set created_at = now() where created_at is null;
update public.user_prefs set updated_at = now() where updated_at is null;

create index if not exists user_prefs_username_lower_idx
  on public.user_prefs (lower(username));
create index if not exists user_prefs_last_active_idx
  on public.user_prefs (last_active desc);

drop trigger if exists user_prefs_set_updated_at on public.user_prefs;
create trigger user_prefs_set_updated_at
before update on public.user_prefs
for each row execute function public.bot_set_updated_at();

-- --------------------------------------------------------------------------
-- 2. Cached Telegram text used by callbacks, history, CRM, and analytics
-- --------------------------------------------------------------------------
create table if not exists public.text_cache (
  id bigint generated by default as identity primary key,
  message_id bigint not null,
  chat_id bigint not null default 0,
  user_id bigint,
  username text,
  original_text text not null,
  content text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint text_cache_chat_message_unique unique (chat_id, message_id)
);

alter table public.text_cache add column if not exists id bigint generated by default as identity;
alter table public.text_cache add column if not exists message_id bigint;
alter table public.text_cache add column if not exists chat_id bigint default 0;
alter table public.text_cache add column if not exists user_id bigint;
alter table public.text_cache add column if not exists username text;
alter table public.text_cache add column if not exists original_text text;
alter table public.text_cache add column if not exists content text;
alter table public.text_cache add column if not exists created_at timestamptz default now();
alter table public.text_cache add column if not exists updated_at timestamptz default now();

-- Required by Supabase upsert(..., on_conflict='chat_id,message_id').
create unique index if not exists text_cache_id_uidx
  on public.text_cache (id);
create unique index if not exists text_cache_chat_message_uidx
  on public.text_cache (chat_id, message_id);
create index if not exists text_cache_user_created_idx
  on public.text_cache (user_id, created_at desc);
create index if not exists text_cache_created_at_idx
  on public.text_cache (created_at desc);

drop trigger if exists text_cache_set_updated_at on public.text_cache;
create trigger text_cache_set_updated_at
before update on public.text_cache
for each row execute function public.bot_set_updated_at();

-- --------------------------------------------------------------------------
-- 3. AI conversation history
-- --------------------------------------------------------------------------
create table if not exists public.conversation_history (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  role text not null,
  content text not null,
  created_at timestamptz not null default now(),
  constraint conversation_history_role_check
    check (role in ('user', 'assistant', 'system'))
);

alter table public.conversation_history add column if not exists id bigint generated by default as identity;
alter table public.conversation_history add column if not exists user_id bigint;
alter table public.conversation_history add column if not exists role text;
alter table public.conversation_history add column if not exists content text;
alter table public.conversation_history add column if not exists created_at timestamptz default now();

create unique index if not exists conversation_history_id_uidx
  on public.conversation_history (id);
create index if not exists conversation_history_user_created_idx
  on public.conversation_history (user_id, created_at desc);

-- --------------------------------------------------------------------------
-- 4. Scheduled Telegram broadcasts
-- --------------------------------------------------------------------------
create table if not exists public.scheduled_broadcasts (
  id bigint generated by default as identity primary key,
  admin_id bigint not null,
  photo_file_id text,
  caption text,
  plain_text text,
  broadcast_at timestamptz not null,
  status text not null default 'pending',
  error_msg text,
  sent_count integer not null default 0,
  failed_count integer not null default 0,
  blocked_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint scheduled_broadcasts_status_check
    check (status in ('pending', 'sending', 'done', 'failed', 'cancelled')),
  constraint scheduled_broadcasts_counts_check
    check (sent_count >= 0 and failed_count >= 0 and blocked_count >= 0)
);

alter table public.scheduled_broadcasts add column if not exists id bigint generated by default as identity;
alter table public.scheduled_broadcasts add column if not exists admin_id bigint;
alter table public.scheduled_broadcasts add column if not exists photo_file_id text;
alter table public.scheduled_broadcasts add column if not exists caption text;
alter table public.scheduled_broadcasts add column if not exists plain_text text;
alter table public.scheduled_broadcasts add column if not exists broadcast_at timestamptz;
alter table public.scheduled_broadcasts add column if not exists status text default 'pending';
alter table public.scheduled_broadcasts add column if not exists error_msg text;
alter table public.scheduled_broadcasts add column if not exists sent_count integer default 0;
alter table public.scheduled_broadcasts add column if not exists failed_count integer default 0;
alter table public.scheduled_broadcasts add column if not exists blocked_count integer default 0;
alter table public.scheduled_broadcasts add column if not exists created_at timestamptz default now();
alter table public.scheduled_broadcasts add column if not exists updated_at timestamptz default now();

update public.scheduled_broadcasts set status = 'pending' where status is null;
update public.scheduled_broadcasts set sent_count = 0 where sent_count is null;
update public.scheduled_broadcasts set failed_count = 0 where failed_count is null;
update public.scheduled_broadcasts set blocked_count = 0 where blocked_count is null;
update public.scheduled_broadcasts set created_at = now() where created_at is null;
update public.scheduled_broadcasts set updated_at = now() where updated_at is null;

create unique index if not exists scheduled_broadcasts_id_uidx
  on public.scheduled_broadcasts (id);
create index if not exists scheduled_broadcasts_status_time_idx
  on public.scheduled_broadcasts (status, broadcast_at);
create index if not exists scheduled_broadcasts_admin_status_time_idx
  on public.scheduled_broadcasts (admin_id, status, broadcast_at);
create index if not exists scheduled_broadcasts_broadcast_at_idx
  on public.scheduled_broadcasts (broadcast_at desc);

drop trigger if exists scheduled_broadcasts_set_updated_at on public.scheduled_broadcasts;
create trigger scheduled_broadcasts_set_updated_at
before update on public.scheduled_broadcasts
for each row execute function public.bot_set_updated_at();

-- --------------------------------------------------------------------------
-- 5. Blocked Telegram users
-- --------------------------------------------------------------------------
create table if not exists public.blocked_users (
  user_id bigint primary key,
  admin_id bigint,
  reason text,
  blocked_at timestamptz not null default now()
);

alter table public.blocked_users add column if not exists admin_id bigint;
alter table public.blocked_users add column if not exists reason text;
alter table public.blocked_users add column if not exists blocked_at timestamptz default now();

create index if not exists blocked_users_blocked_at_idx
  on public.blocked_users (blocked_at desc);

-- --------------------------------------------------------------------------
-- 6. Runtime bot settings
-- --------------------------------------------------------------------------
create table if not exists public.bot_settings (
  key text primary key,
  value text not null,
  updated_by bigint,
  updated_at timestamptz not null default now()
);

alter table public.bot_settings add column if not exists value text;
alter table public.bot_settings add column if not exists updated_by bigint;
alter table public.bot_settings add column if not exists updated_at timestamptz default now();

drop trigger if exists bot_settings_set_updated_at on public.bot_settings;
create trigger bot_settings_set_updated_at
before update on public.bot_settings
for each row execute function public.bot_set_updated_at();

insert into public.bot_settings (key, value) values
  ('maintenance_mode', '0'),
  ('tts_enabled', '1'),
  ('ocr_enabled', '1'),
  ('voice_transcribe_enabled', '1'),
  ('audio_transcribe_enabled', '1'),
  ('audio_to_voice_enabled', '1'),
  ('ai_resolver_enabled', '1'),
  ('TELEGRAM_CONCURRENT_UPDATES', '4'),
  ('TELEGRAM_CONNECTION_POOL_SIZE', '24'),
  ('HTTP_MAX_CONNECTIONS', '100'),
  ('HTTP_MAX_KEEPALIVE_CONNECTIONS', '20'),
  ('DB_EXECUTOR_MAX_WORKERS', '3'),
  ('MAX_CONCURRENT_TTS_USERS', '2'),
  ('USER_SYNC_TTL_S', '1800.0'),
  ('PREFS_CACHE_TTL_S', '600.0'),
  ('TTS_AUDIO_CACHE_ENABLED', '1'),
  ('TTS_AUDIO_CACHE_MAX_MB', '64'),
  ('TTS_AUDIO_CACHE_ITEM_MAX_MB', '8'),
  ('TTS_AUDIO_CACHE_TTL_S', '1200.0'),
  ('EDGE_TTS_PARALLEL_CHUNKS', '1'),
  ('PAGED_TTS_SEND_DELAY_S', '0.10'),
  ('WEB_STATUS_POLL_SECONDS', '30'),
  ('WEB_LIVE_POLL_SECONDS', '30')
on conflict (key) do nothing;

-- --------------------------------------------------------------------------
-- 7. Distributed scheduler / active-server locks
-- --------------------------------------------------------------------------
create table if not exists public.bot_locks (
  lock_key text primary key,
  owner text not null,
  locked_until timestamptz not null,
  updated_at timestamptz not null default now()
);

alter table public.bot_locks add column if not exists owner text;
alter table public.bot_locks add column if not exists locked_until timestamptz;
alter table public.bot_locks add column if not exists updated_at timestamptz default now();

create index if not exists bot_locks_locked_until_idx
  on public.bot_locks (locked_until);

-- --------------------------------------------------------------------------
-- 8. Hashed AI API keys generated by bot admins
-- --------------------------------------------------------------------------
create table if not exists public.ai_api_keys (
  id bigint generated by default as identity primary key,
  key_prefix text not null,
  key_hash text not null unique,
  admin_id bigint not null,
  note text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  last_used_at timestamptz
);

alter table public.ai_api_keys add column if not exists id bigint generated by default as identity;
alter table public.ai_api_keys add column if not exists key_prefix text;
alter table public.ai_api_keys add column if not exists key_hash text;
alter table public.ai_api_keys add column if not exists admin_id bigint;
alter table public.ai_api_keys add column if not exists note text;
alter table public.ai_api_keys add column if not exists active boolean default true;
alter table public.ai_api_keys add column if not exists created_at timestamptz default now();
alter table public.ai_api_keys add column if not exists revoked_at timestamptz;
alter table public.ai_api_keys add column if not exists last_used_at timestamptz;

create unique index if not exists ai_api_keys_id_uidx
  on public.ai_api_keys (id);
create unique index if not exists ai_api_keys_key_hash_uidx
  on public.ai_api_keys (key_hash);
create index if not exists ai_api_keys_active_idx
  on public.ai_api_keys (active);
create index if not exists ai_api_keys_created_at_idx
  on public.ai_api_keys (created_at desc);

-- --------------------------------------------------------------------------
-- 9. Feature requests submitted by users
-- --------------------------------------------------------------------------
create table if not exists public.feature_requests (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id bigint not null,
  title text,
  detail text not null,
  status text not null default 'new',
  admin_note text,
  similar_key text,
  votes integer not null default 1,
  priority integer not null default 0,
  source text not null default 'open_answer',
  language text,
  completed_at timestamptz,
  notified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint feature_requests_status_check
    check (status in (
      'new', 'reviewing', 'accepted', 'planned', 'in_progress',
      'completed', 'later', 'rejected', 'duplicate'
    )),
  constraint feature_requests_votes_check check (votes >= 0)
);

alter table public.feature_requests add column if not exists id uuid default extensions.gen_random_uuid();
alter table public.feature_requests add column if not exists user_id bigint;
alter table public.feature_requests add column if not exists title text;
alter table public.feature_requests add column if not exists detail text;
alter table public.feature_requests add column if not exists status text default 'new';
alter table public.feature_requests add column if not exists admin_note text;
alter table public.feature_requests add column if not exists similar_key text;
alter table public.feature_requests add column if not exists votes integer default 1;
alter table public.feature_requests add column if not exists priority integer default 0;
alter table public.feature_requests add column if not exists source text default 'open_answer';
alter table public.feature_requests add column if not exists language text;
alter table public.feature_requests add column if not exists completed_at timestamptz;
alter table public.feature_requests add column if not exists notified_at timestamptz;
alter table public.feature_requests add column if not exists created_at timestamptz default now();
alter table public.feature_requests add column if not exists updated_at timestamptz default now();

create unique index if not exists feature_requests_id_uidx
  on public.feature_requests (id);
create index if not exists feature_requests_status_updated_idx
  on public.feature_requests (status, updated_at desc);
create index if not exists feature_requests_user_created_idx
  on public.feature_requests (user_id, created_at desc);
create index if not exists feature_requests_similar_key_idx
  on public.feature_requests (similar_key);

drop trigger if exists feature_requests_set_updated_at on public.feature_requests;
create trigger feature_requests_set_updated_at
before update on public.feature_requests
for each row execute function public.bot_set_updated_at();

-- --------------------------------------------------------------------------
-- Row Level Security
-- The bot is server-side only. No anon/authenticated access is granted.
-- --------------------------------------------------------------------------
alter table public.user_prefs enable row level security;
alter table public.text_cache enable row level security;
alter table public.conversation_history enable row level security;
alter table public.scheduled_broadcasts enable row level security;
alter table public.blocked_users enable row level security;
alter table public.bot_settings enable row level security;
alter table public.bot_locks enable row level security;
alter table public.ai_api_keys enable row level security;
alter table public.feature_requests enable row level security;

revoke all on table
  public.user_prefs,
  public.text_cache,
  public.conversation_history,
  public.scheduled_broadcasts,
  public.blocked_users,
  public.bot_settings,
  public.bot_locks,
  public.ai_api_keys,
  public.feature_requests
from anon, authenticated;

grant select, insert, update, delete on table
  public.user_prefs,
  public.text_cache,
  public.conversation_history,
  public.scheduled_broadcasts,
  public.blocked_users,
  public.bot_settings,
  public.bot_locks,
  public.ai_api_keys,
  public.feature_requests
to service_role;

grant usage, select on all sequences in schema public to service_role;

-- Policies are explicit for clarity. A correctly configured service-role key
-- also bypasses RLS, but the bot must still remain server-side.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'user_prefs',
    'text_cache',
    'conversation_history',
    'scheduled_broadcasts',
    'blocked_users',
    'bot_settings',
    'bot_locks',
    'ai_api_keys',
    'feature_requests'
  ]
  loop
    execute format('drop policy if exists %I on public.%I', 'service_role_' || table_name || '_all', table_name);
    execute format(
      'create policy %I on public.%I for all to service_role using (true) with check (true)',
      'service_role_' || table_name || '_all',
      table_name
    );
  end loop;
end
$$;

-- Ask PostgREST to reload the schema after new columns/tables are created.
notify pgrst, 'reload schema';

commit;

-- --------------------------------------------------------------------------
-- Verification: this should return 9 rows, each with table_exists = true.
-- --------------------------------------------------------------------------
select required.table_name,
       to_regclass('public.' || required.table_name) is not null as table_exists
from (
  values
    ('user_prefs'),
    ('text_cache'),
    ('conversation_history'),
    ('scheduled_broadcasts'),
    ('blocked_users'),
    ('bot_settings'),
    ('bot_locks'),
    ('ai_api_keys'),
    ('feature_requests')
) as required(table_name)
order by required.table_name;
