"""Centralized application settings and feature flags."""

from __future__ import annotations

from app.core.config import (
    FEATURE_AI_CHAT,
    FEATURE_ARTICLE_READER,
    FEATURE_AUDIO_TRANSCRIPTION,
    FEATURE_CHANNEL_NARRATOR,
    FEATURE_DONATION,
    FEATURE_OCR,
    FEATURE_PODCAST,
    FEATURE_TIKTOK,
    FEATURE_TTS,
    SETTINGS,
    AppSettings,
    get_detected_webhook_url,
    get_feature_flags,
    is_ai_chat_enabled,
    is_article_reader_enabled,
    is_audio_transcription_enabled,
    is_channel_narrator_enabled,
    is_donation_enabled,
    is_feature_enabled,
    is_ocr_enabled,
    is_podcast_enabled,
    is_tiktok_enabled,
    is_tts_enabled,
    reset_feature_overrides,
    set_feature_override,
)

__all__ = [
    "FEATURE_AI_CHAT",
    "FEATURE_ARTICLE_READER",
    "FEATURE_AUDIO_TRANSCRIPTION",
    "FEATURE_CHANNEL_NARRATOR",
    "FEATURE_DONATION",
    "FEATURE_OCR",
    "FEATURE_PODCAST",
    "FEATURE_TIKTOK",
    "FEATURE_TTS",
    "SETTINGS",
    "AppSettings",
    "get_detected_webhook_url",
    "get_feature_flags",
    "is_ai_chat_enabled",
    "is_article_reader_enabled",
    "is_audio_transcription_enabled",
    "is_channel_narrator_enabled",
    "is_donation_enabled",
    "is_feature_enabled",
    "is_ocr_enabled",
    "is_podcast_enabled",
    "is_tiktok_enabled",
    "is_tts_enabled",
    "reset_feature_overrides",
    "set_feature_override",
]
